services:
  clone:
    container_name: clone
    build: .
    image: git:v1
    environment:
      - GIT_REPOSITORY="git@github.com:nightarcherbr/cake.git"
      - GIT_TIMEOUT=120
      - GIT_TARGET=/var/www/cake
      - SSH_KEYFILE=/usr/local/bin/id_rsa
    volumes:
      - .:/usr/local/bin